### ISSUE TITLE
Request: Medic ability to pick up weapons as a cvar

### ISSUE THREAD

**Issue by texnofobix** [InFerYes/dday#12]
Old behavior let medics pick up weapons. It was removed at one point. Ideally it could be a setting.

**Comment by InFerYes** [comment]
Solved with https://github.com/InFerYes/dday/commit/ab23234eaa95e7b553337253ab043f8b901f06ba

The setting is `allow_medic_pickup` and is default to 0. 

If you set it to `1` the medic can pickup any weapon. If set to `0` the medic can only pickup his own type of weapons (pistol, knife and helmet).
