### ISSUE TITLE
Long grenade throw by default?

### ISSUE THREAD

**Issue by ed65536** [InFerYes/dday#14]
I rarely use the short grenade throw, perhaps 1 time out of 10. I almost always go for the select grenade + mouse2 combo to select long throw, and switch back to short only if the situation demands it. On 11th of December, there were a bunch of new players from action q2, who found this situation strange, and they were often getting fragged from afar. I suspect it takes a bit to get used to. It is possible to bind the auto-select of long throw, but if the long throw is superior anyway, it could make sense to just make it the default option upon selecting grenades. 

It is of course a matter of debate.

**Comment by MrG-DRGN** [comment]
Closed

**Comment by InFerYes** [comment]
Fixed with https://github.com/InFerYes/dday/commit/1856f1b84e2d68b040480682cb909a15e8aa844d (and https://github.com/InFerYes/dday/commit/774a5af1ec15c50a0c51e5e7752ca0416da37851)
