### ISSUE TITLE
All gun magazines start with 0 or 3 rounds

### ISSUE THREAD

**Issue by ed65536** [InFerYes/dday#5]
https://github.com/InFerYes/dday/commit/357cde9330a557923a79406098ccfe6ab9a111c5
(at least both the Windows and the ARMv7 build)

- every weapon starts with 0 or 3 rounds in a magazine, but they all seem to work well otherwise (after the first reload). So they are missing the first full clip. This also affects the bots -- the bots might not fire at you instantly (and might run past you), but will fire once they make up their mind and reload.

**Comment by MrG-DRGN** [comment]
Resolved
